const API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-membership';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0});
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=localStorage.getItem('d12m_v21_token')||'';
let role=localStorage.getItem('d12m_v21_role')||'';
let data=null;
let page='dashboard';
let searchTerm='';
let toastTimer=null;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function setTheme(){try{if(localStorage.d12theme==='dark')document.documentElement.classList.add('dark')}catch(e){}}
function toggleTheme(){document.documentElement.classList.toggle('dark');localStorage.d12theme=document.documentElement.classList.contains('dark')?'dark':'light'}
setTheme();
async function request(action,payload={},useAuth=true){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(useAuth&&token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(r.status===401&&useAuth&&action!=='staff_login'&&action!=='member_login'){logoutLocal(false)}if(!r.ok||!j.ok)throw new Error(j.error||'Request failed.');return j}
function saveSession(j){token=j.token;role=j.role;localStorage.setItem('d12m_v21_token',token);localStorage.setItem('d12m_v21_role',role)}
function logoutLocal(showWelcome=true){token='';role='';data=null;localStorage.removeItem('d12m_v21_token');localStorage.removeItem('d12m_v21_role');$('#app').classList.add('hidden');$('#publicStatus').classList.add('hidden');if(showWelcome){$('#welcome').classList.remove('hidden');$('#loginPanel').classList.add('hidden')}}
async function logout(){try{await request('logout')}catch(e){}logoutLocal(true)}
function chooseLogin(kind){const panel=$('#loginPanel');panel.classList.remove('hidden');if(kind==='member'){panel.innerHTML=`<div class="login-panel-head"><div><h2>Member Login</h2><div class="muted tiny">View only your own membership.</div></div><button class="icon-btn" onclick="closeLoginPanel()">×</button></div><form id="memberLoginForm"><div class="field"><label>MEMBER ID</label><input name="member_code" placeholder="D12-2026-123456" required autocomplete="username"></div><div class="field" style="margin-top:10px"><label>PHONE OR EMAIL</label><input name="credential" required autocomplete="current-password"></div><button class="btn good block" style="margin-top:12px">View My Membership</button><div id="loginError" class="login-error"></div></form>`;$('#memberLoginForm').addEventListener('submit',memberLoginSubmit)}else{const isAdmin=kind==='admin';panel.innerHTML=`<div class="login-panel-head"><div><h2>${isAdmin?'Admin':'User'} Login</h2><div class="muted tiny">${isAdmin?'Full system control.':'Registration and membership status access.'}</div></div><button class="icon-btn" onclick="closeLoginPanel()">×</button></div><form id="staffLoginForm"><input type="hidden" name="role" value="${kind}"><div class="field"><label>PASSWORD</label><input name="password" type="password" required autocomplete="current-password" autofocus></div><button class="btn ${isAdmin?'primary':'purple'} block" style="margin-top:12px">Sign In</button><div id="loginError" class="login-error"></div></form>`;$('#staffLoginForm').addEventListener('submit',staffLoginSubmit);setTimeout(()=>$('#staffLoginForm input[name=password]')?.focus(),50)}panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
function closeLoginPanel(){$('#loginPanel').classList.add('hidden')}
async function staffLoginSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),err=$('#loginError');err.textContent='';try{const j=await request('staff_login',{role:f.get('role'),password:f.get('password')},false);saveSession(j);await enterApp()}catch(x){err.textContent=x.message}}
async function memberLoginSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),err=$('#loginError');err.textContent='';try{const j=await request('member_login',{member_code:f.get('member_code'),credential:f.get('credential')},false);saveSession(j);await enterApp()}catch(x){err.textContent=x.message}}
async function enterApp(){$('#welcome').classList.add('hidden');$('#publicStatus').classList.add('hidden');$('#app').classList.remove('hidden');const j=await request('bootstrap');data=j;role=j.role;localStorage.setItem('d12m_v21_role',role);page=role==='admin'?'dashboard':role==='user'?'status':'member';render()}
function navItems(){if(role==='admin')return [['dashboard','⌂','Dashboard'],['members','♙','Members'],['payments','₦','Payments'],['renewals','↻','Renewals'],['scanner','▥','Scanner'],['settings','⚙','Settings']];if(role==='user')return [['register','＋','Register'],['status','♙','Status'],['scanner','▥','Scanner']];return[]}
function go(p){page=p;render()}
function setNav(){const items=navItems(),html=items.map(([p,i,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')">${i} &nbsp;${l}</button>`).join('');$('#nav').innerHTML=html;$('#mobileNav').innerHTML=items.map(([p,i,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')">${i}<br>${l}</button>`).join('');$('#mobileNav').style.setProperty('--nav-count',Math.max(items.length,1));$('#roleBadge').textContent=(role||'').toUpperCase()+' ACCESS'}
function statusOf(m){if(m.membership_status)return{label:m.membership_status,days:m.days_remaining,cls:m.membership_status==='ACTIVE'?'active':m.membership_status==='EXPIRING SOON'?'soon':m.membership_status==='EXPIRED'?'expired':'inactive'};const w=Number(data?.settings?.expiring_soon_days||7);if(!m.expiry_date)return{label:'INACTIVE',days:null,cls:'inactive'};const t=new Date();t.setHours(0,0,0,0);const e=new Date(m.expiry_date+'T00:00:00'),days=Math.floor((e-t)/86400000)+1;if(days<=0)return{label:'EXPIRED',days:0,cls:'expired'};if(days<=w)return{label:'EXPIRING SOON',days,cls:'soon'};return{label:'ACTIVE',days,cls:'active'}}
function pill(m){const s=statusOf(m);return`<span class="pill ${s.cls}">${esc(s.label)}</span>`}
function memberStatusTable(rows,adminActions=false){if(!rows.length)return`<div class="empty">No matching members.</div>`;return`<div class="table-wrap"><table><thead><tr><th>Member</th><th>Phone</th><th>Plan</th><th>Expiry</th><th>Days</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(m=>{const s=statusOf(m),phone=(m.phone||'').replace(/\D/g,'').replace(/^0/,'234');return`<tr><td><b>${esc(m.full_name)}</b><br><small>${esc(m.member_code)}</small></td><td>${esc(m.phone||'—')}</td><td>${esc(m.current_plan_name||'—')}</td><td>${esc(m.expiry_date||'—')}</td><td>${s.days??'—'}</td><td>${pill(m)}</td><td><div class="table-actions"><button class="btn small" onclick="openCard('${m.id}')">Card</button>${phone?`<a class="btn small" target="_blank" rel="noopener" href="https://wa.me/${phone}">WhatsApp</a>`:''}${adminActions?`<button class="btn small danger" onclick="archiveMember('${m.id}')">Archive</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div>`}
function filteredMembers(){const rows=data?.members||[];if(!searchTerm)return rows;const q=searchTerm.toLowerCase();return rows.filter(m=>[m.full_name,m.member_code,m.phone,m.email,m.current_plan_name].some(v=>String(v||'').toLowerCase().includes(q)))}
function searchInput(){return`<div class="field searchbox"><label>SEARCH MEMBERS</label><input id="memberSearch" value="${esc(searchTerm)}" placeholder="Name, ID, phone or plan"></div>`}
function attachSearch(){const el=$('#memberSearch');if(el)el.addEventListener('input',e=>{searchTerm=e.target.value;renderViewOnly()})}
function dashboardView(){const ms=data.members||[],ps=data.payments||[];const active=ms.filter(m=>['ACTIVE','EXPIRING SOON'].includes(statusOf(m).label)).length,soon=ms.filter(m=>statusOf(m).label==='EXPIRING SOON').length,expired=ms.filter(m=>statusOf(m).label==='EXPIRED').length,revenue=ps.filter(p=>p.payment_status==='Paid').reduce((a,p)=>a+Number(p.amount),0),watch=ms.filter(m=>['EXPIRING SOON','EXPIRED'].includes(statusOf(m).label)).slice(0,10);return`<div class="grid kpis"><div class="card kpi"><span>ACTIVE MEMBERS</span><b>${active}</b></div><div class="card kpi"><span>EXPIRING SOON</span><b>${soon}</b></div><div class="card kpi"><span>EXPIRED</span><b>${expired}</b></div><div class="card kpi"><span>VERIFIED REVENUE</span><b>${money(revenue)}</b></div></div><div class="card section"><h2>Renewal Watch</h2>${memberStatusTable(watch,false)}</div><div class="card section"><div class="notice">Expired members return to the ${money(data.settings?.daily_rate||3000)} daily rate until renewal. Membership is personal and non-transferable. Tournaments, special events and VIP/challenge charges are separate.</div></div>`}
function membersView(adminMode){return`<div class="card section"><div class="row" style="justify-content:space-between"><div><h2>Members</h2><div class="muted tiny">Register members, view status and issue membership cards.</div></div><button class="btn primary" onclick="openMemberModal()">＋ Register Member</button></div><div style="margin-top:14px">${searchInput()}${memberStatusTable(filteredMembers(),adminMode)}</div>${adminMode?`<div class="row" style="margin-top:14px"><div class="field"><label>IMPORT CSV</label><input id="csvFile" type="file" accept=".csv,text/csv"></div><button class="btn" onclick="importCsv()">Import Members</button><button class="btn" onclick="exportCsv()">Export Status CSV</button></div>`:''}</div>`}
function userRegisterView(){return`<div class="card section"><h2>Register a New Member</h2><p class="muted">Create the member record and membership card. Payments and activation remain Admin-only.</p><button class="btn primary" onclick="openMemberModal()">＋ Open Registration Form</button></div><div class="card section"><h2>Recently Registered / Member Status</h2>${memberStatusTable((data.members||[]).slice(0,8),false)}</div>`}
function paymentsView(){const activePlans=(data.plans||[]).filter(p=>p.active&&p.price),ms=data.members||[],ps=data.payments||[];return`<div class="card section"><h2>Record Payment</h2><form id="paymentForm"><div class="row"><div class="field"><label>MEMBER *</label><select name="member_id" required><option value="">Select member</option>${ms.map(m=>`<option value="${m.id}">${esc(m.full_name)} — ${esc(m.member_code)}</option>`).join('')}</select></div><div class="field"><label>PLAN *</label><select name="plan_id" required><option value="">Select plan</option>${activePlans.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('')}</select></div><div class="field"><label>AMOUNT *</label><input name="amount" type="number" min="1" required></div><div class="field"><label>PAYMENT DATE</label><input name="payment_date" type="date" value="${today()}"></div><div class="field"><label>METHOD</label><select name="payment_method"><option>Transfer</option><option>Cash</option><option>POS</option><option>Other</option></select></div><div class="field"><label>REFERENCE</label><input name="reference"></div></div><div class="notice" style="margin-top:12px">Payment stays Pending until Admin verifies it and sets the Activation Date.</div><button class="btn primary" style="margin-top:12px">Record as Pending</button></form></div><div class="card section"><h2>Payment Register</h2><div class="table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Amount</th><th>Status</th><th>Paid</th><th>Activation</th><th>Action</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.d12_membership_members?.full_name||'Unknown')}</td><td>${esc(p.d12_membership_plans?.name||'—')}</td><td><b>${money(p.amount)}</b></td><td>${esc(p.payment_status)}</td><td>${esc(p.payment_date||'—')}</td><td>${esc(p.activation_date||'—')}</td><td>${p.payment_status==='Pending'?`<div class="table-actions"><input id="act-${p.id}" type="date" value="${today()}" style="min-height:38px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--text);padding:5px"><button class="btn small good" onclick="verifyPayment('${p.id}')">Verify</button><button class="btn small danger" onclick="rejectPayment('${p.id}')">Reject</button></div>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function renewalsView(){const rows=(data.members||[]).filter(m=>['EXPIRING SOON','EXPIRED'].includes(statusOf(m).label)).sort((a,b)=>(statusOf(a).days??9999)-(statusOf(b).days??9999));return`<div class="card section"><h2>Renewal Queue</h2>${memberStatusTable(rows,false)}</div>`}
function scannerView(){return`<div class="card section scanner-wrap"><h2>Scan Membership Card</h2><p class="muted">Keep this screen open and scan the Code 128 barcode on a D12 membership card. The membership summary appears immediately.</p><form id="scanForm"><div class="field"><label>BARCODE</label><input id="scanInput" class="scan-input" autocomplete="off" autofocus placeholder="Scan or enter D12M token"></div><button class="btn primary" style="margin-top:10px">Check Card</button></form><div id="scanResult" class="scanner-result"></div></div>`}
function settingsView(){return`<div class="card section"><h2>Club Rates & Alerts</h2><form id="settingsForm"><div class="row"><div class="field"><label>DAILY RATE AFTER EXPIRY (₦)</label><input name="daily_rate" type="number" min="0" value="${Number(data.settings?.daily_rate||3000)}" required></div><div class="field"><label>EXPIRING SOON WINDOW (DAYS)</label><input name="expiring_soon_days" type="number" min="1" max="60" value="${Number(data.settings?.expiring_soon_days||7)}" required></div></div><button class="btn primary" style="margin-top:12px">Save Club Settings</button></form></div><div class="card section"><h2>Membership Plans</h2><div class="grid plans">${(data.plans||[]).map(p=>`<form class="card plan planForm" data-id="${p.id}"><h3>${esc(p.name)}</h3><div class="muted tiny">${p.period_value} ${esc(p.period_unit)}</div><div class="field" style="margin-top:10px"><label>PRICE (₦)</label><input name="price" type="number" min="1" value="${p.price||''}" placeholder="Set price"></div><label style="display:flex;gap:8px;align-items:center;margin-top:10px"><input name="active" type="checkbox" style="width:auto" ${p.active?'checked':''}> Active plan</label><button class="btn block" style="margin-top:10px">Save Plan</button></form>`).join('')}</div></div><div class="card section"><h2>User Login Password</h2><p class="muted">The User role can only register members and view membership status. Changing this password signs out all current User sessions.</p><form id="userPasswordForm"><div class="row"><div class="field"><label>NEW USER PASSWORD</label><input name="new_password" type="password" minlength="4" required autocomplete="new-password"></div><div class="field"><label>CONFIRM PASSWORD</label><input name="confirm_password" type="password" minlength="4" required autocomplete="new-password"></div></div><button class="btn purple" style="margin-top:12px">Change User Password</button></form></div>`}
function memberPortalView(){const m=data.member,s=statusOf(m);return`<div class="card status-hero"><div class="row" style="justify-content:space-between;align-items:center"><div><div class="muted tiny">MY D12 MEMBERSHIP</div><h2>${esc(m.full_name)}</h2><div class="muted">${esc(m.member_code)}</div></div>${pill(m)}</div><div class="status-grid"><div class="status-item"><span>MEMBERSHIP TYPE</span><b>${esc(m.current_plan_name||'Not active')}</b></div><div class="status-item"><span>EXPIRATION DATE</span><b>${esc(m.expiry_date||'—')}</b></div><div class="status-item"><span>DAYS REMAINING</span><b>${s.days??'—'}</b></div><div class="status-item"><span>ACTIVATION DATE</span><b>${esc(m.activation_date||'—')}</b></div></div>${s.label==='EXPIRED'?`<div class="notice" style="margin-top:14px">Your membership has expired. The current daily play rate is ${money(data.settings?.daily_rate||3000)} until renewal.</div>`:''}<div class="row" style="margin-top:16px"><button class="btn primary" onclick="openCard('${m.id}')">View Membership Card</button><button class="btn" onclick="toggleTheme()">◐ Theme</button><button class="btn danger" onclick="logout()">Sign Out</button></div></div>`}
function render(){setNav();renderViewOnly()}
function renderViewOnly(){const title=$('#pageTitle'),sub=$('#pageSub'),view=$('#view'),actions=$('#topActions');if(role==='member'){title.textContent='My Membership';sub.textContent='Your personal D12 membership status.';actions.innerHTML=`<button class="btn" onclick="toggleTheme()">◐ Theme</button><button class="btn danger" onclick="logout()">Sign Out</button>`;view.innerHTML=memberPortalView();return}const map={dashboard:['Dashboard','Membership health at a glance.'],members:['Members','Register, review and issue membership cards.'],payments:['Payments','Verify payments before activation.'],renewals:['Renewals','Members who need renewal attention.'],scanner:['Card Scanner','Scan a membership card to view status.'],settings:['Settings','Admin-only rates, plans and login controls.'],register:['Register Members','Create new member records and cards.'],status:['Membership Status','View member status without payment or settings access.']},meta=map[page]||map.status;title.textContent=meta[0];sub.textContent=meta[1];actions.innerHTML=`<button class="btn" onclick="toggleTheme()">◐ Theme</button>${role!=='member'?`<button class="btn wide" onclick="openMemberModal()">＋ Member</button>`:''}${role==='admin'?`<button class="btn primary wide" onclick="go('payments')">＋ Payment</button>`:''}<button class="btn danger" onclick="logout()">Sign Out</button>`;if(page==='dashboard')view.innerHTML=dashboardView();else if(page==='members')view.innerHTML=membersView(true);else if(page==='payments')view.innerHTML=paymentsView();else if(page==='renewals')view.innerHTML=renewalsView();else if(page==='scanner')view.innerHTML=scannerView();else if(page==='settings')view.innerHTML=settingsView();else if(page==='register')view.innerHTML=userRegisterView();else view.innerHTML=`<div class="card section"><h2>Member Status</h2>${searchInput()}${memberStatusTable(filteredMembers(),false)}</div>`;wireCurrentView()}
function wireCurrentView(){attachSearch();if($('#paymentForm'))$('#paymentForm').addEventListener('submit',recordPayment);if($('#scanForm')){$('#scanForm').addEventListener('submit',scanCard);setTimeout(()=>$('#scanInput')?.focus(),40)}if($('#settingsForm'))$('#settingsForm').addEventListener('submit',saveSettings);$$('.planForm').forEach(f=>f.addEventListener('submit',savePlan));if($('#userPasswordForm'))$('#userPasswordForm').addEventListener('submit',changeUserPassword)}
function openMemberModal(){$('#memberModal').classList.remove('hidden');setTimeout(()=>$('#memberForm input[name=full_name]')?.focus(),40)}
function closeModal(id){$('#'+id).classList.add('hidden')}
async function registerMember(e){e.preventDefault();const f=new FormData(e.currentTarget),payload=Object.fromEntries(f.entries());try{const j=await request('add_member',payload);e.currentTarget.reset();closeModal('memberModal');await refresh();toast('Member registered and card created.');openCard(j.member.id)}catch(x){toast(x.message)}}
async function refresh(){data=await request('bootstrap');role=data.role;render()}
async function archiveMember(id){if(!confirm('Archive this member? Payment history will remain.'))return;try{await request('archive_member',{id});await refresh();toast('Member archived.')}catch(x){toast(x.message)}}
async function recordPayment(e){e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget).entries());try{await request('record_payment',payload);await refresh();toast('Payment recorded as Pending.')}catch(x){toast(x.message)}}
async function verifyPayment(id){const activation=$('#act-'+CSS.escape(id))?.value;if(!activation)return toast('Select activation date.');try{const j=await request('verify_payment',{id,activation_date:activation});await refresh();toast('Membership active until '+j.expiry_date)}catch(x){toast(x.message)}}
async function rejectPayment(id){if(!confirm('Reject this pending payment?'))return;try{await request('reject_payment',{id});await refresh();toast('Payment rejected.')}catch(x){toast(x.message)}}
async function saveSettings(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await request('save_settings',{daily_rate:Number(f.get('daily_rate')),expiring_soon_days:Number(f.get('expiring_soon_days'))});await refresh();toast('Settings saved.')}catch(x){toast(x.message)}}
async function savePlan(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await request('save_plan',{id:e.currentTarget.dataset.id,price:Number(f.get('price')||0),active:f.get('active')==='on'});await refresh();toast('Plan saved.')}catch(x){toast(x.message)}}
async function changeUserPassword(e){e.preventDefault();const f=new FormData(e.currentTarget),p=String(f.get('new_password')||''),c=String(f.get('confirm_password')||'');if(p!==c)return toast('Passwords do not match.');try{await request('change_user_password',{new_password:p});e.currentTarget.reset();toast('User password changed. Existing User sessions signed out.')}catch(x){toast(x.message)}}
function cardStatusHtml(m,dailyRate=null){const s=statusOf(m);return`<div class="card status-hero"><div class="row" style="justify-content:space-between;align-items:center"><div><div class="muted tiny">D12 MEMBERSHIP STATUS</div><h2>${esc(m.full_name)}</h2><div class="muted">${esc(m.member_code)}</div></div>${pill(m)}</div><div class="status-grid"><div class="status-item"><span>MEMBERSHIP TYPE</span><b>${esc(m.current_plan_name||'Not active')}</b></div><div class="status-item"><span>EXPIRATION DATE</span><b>${esc(m.expiry_date||'—')}</b></div><div class="status-item"><span>DAYS REMAINING</span><b>${s.days??'—'}</b></div><div class="status-item"><span>ACTIVATION DATE</span><b>${esc(m.activation_date||'—')}</b></div></div>${s.label==='EXPIRED'&&dailyRate!=null?`<div class="notice" style="margin-top:14px">Expired membership: current daily rate is ${money(dailyRate)} until renewal.</div>`:''}</div>`}
async function scanCard(e){e.preventDefault();const raw=$('#scanInput').value.trim(),card_token=raw.replace(/^D12M:/i,'').replace(/^.*[?&]card=/,'').split('&')[0];if(!card_token)return;$('#scanResult').innerHTML='<div class="notice">Checking card…</div>';try{const j=await request('card_status',{card_token},false);$('#scanResult').innerHTML=cardStatusHtml(j.member,j.daily_rate);$('#scanInput').value='';$('#scanInput').focus()}catch(x){$('#scanResult').innerHTML=`<div class="notice" style="color:var(--red)">${esc(x.message)}</div>`}}
function openCard(id){const pool=role==='member'?[data.member]:(data.members||[]),m=pool.find(x=>x.id===id);if(!m)return toast('Member card not found.');const s=statusOf(m),loginUrl=location.origin+location.pathname,liveUrl=loginUrl+'?card='+encodeURIComponent(m.card_token||'');$('#cardMount').innerHTML=`<div id="printCard" class="membership-card"><div class="mc-head"><div class="mc-logo">D12 CUE CLUB<small>OFFICIAL MEMBERSHIP CARD</small></div><div class="mc-status">${esc(s.label)}</div></div><div class="mc-name">${esc(m.full_name)}</div><div class="mc-id">MEMBER ID · ${esc(m.member_code)}</div><div class="mc-grid"><div><span>MEMBERSHIP</span><b>${esc(m.current_plan_name||'INACTIVE')}</b></div><div><span>EXPIRES</span><b>${esc(m.expiry_date||'—')}</b></div><div><span>DAYS LEFT</span><b>${s.days??'—'}</b></div></div><a href="${esc(liveUrl)}" target="_blank" rel="noopener" title="Open live membership status"><div class="barcode-box"><svg id="memberBarcode"></svg></div></a><div class="mc-foot"><span>SCAN AT D12 TO CHECK STATUS</span><span>${esc(loginUrl.replace(/^https?:\/\//,''))}</span></div></div><div class="card-tools"><button class="btn primary" onclick="printCard()">Print Card</button><a class="btn" href="${esc(liveUrl)}" target="_blank" rel="noopener">Open Live Status</a></div>`;$('#cardModal').classList.remove('hidden');setTimeout(()=>{try{if(window.JsBarcode&&m.card_token)JsBarcode('#memberBarcode','D12M:'+m.card_token,{format:'CODE128',displayValue:false,height:55,width:1.3,margin:0,background:'#ffffff',lineColor:'#000000'})}catch(e){console.error(e)}},60)}
function printCard(){window.print()}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const head=lines.shift().split(',').map(x=>x.trim().toLowerCase());return lines.map(line=>{const cols=line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')),r={};head.forEach((h,i)=>r[h]=cols[i]||'');return r})}
async function importCsv(){const file=$('#csvFile')?.files?.[0];if(!file)return toast('Choose a CSV file.');try{const rows=parseCsv(await file.text()),j=await request('import_members',{rows});await refresh();toast(`${j.count} members imported.`)}catch(x){toast(x.message)}}
function exportCsv(){const rows=data.members||[],head=['Member ID','Name','Phone','Email','Plan','Expiry','Days Remaining','Status'],csv=[head,...rows.map(m=>{const s=statusOf(m);return[m.member_code,m.full_name,m.phone||'',m.email||'',m.current_plan_name||'',m.expiry_date||'',s.days??'',s.label]})].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='D12_Membership_Status.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function showPublicCard(cardToken){$('#welcome').classList.add('hidden');$('#app').classList.add('hidden');$('#publicStatus').classList.remove('hidden');$('#publicStatus').innerHTML='<div class="welcome"><div class="welcome-head"><div class="welcome-logo">D12</div><h1>Checking Card</h1><p>Loading live membership status…</p></div></div>';try{const j=await request('card_status',{card_token:cardToken},false);$('#publicStatus').innerHTML=`<div class="welcome"><header class="welcome-head"><div class="welcome-logo">D12</div><h1>Membership Status</h1><p>Live D12 Cue Club card verification.</p></header>${cardStatusHtml(j.member,j.daily_rate)}<div class="center" style="margin-top:16px"><button class="btn" onclick="location.href=location.pathname">Back to Login</button></div></div>`}catch(x){$('#publicStatus').innerHTML=`<div class="welcome"><header class="welcome-head"><div class="welcome-logo">D12</div><h1>Card Not Verified</h1><p>${esc(x.message)}</p></header><div class="center"><button class="btn" onclick="location.href=location.pathname">Back to Login</button></div></div>`}}
$$('[data-login]').forEach(b=>b.addEventListener('click',()=>chooseLogin(b.dataset.login)));
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
$('#memberForm').addEventListener('submit',registerMember);
window.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal').forEach(m=>m.classList.add('hidden'))});
(async()=>{const cardToken=new URLSearchParams(location.search).get('card');if(cardToken){await showPublicCard(cardToken);return}if(token){try{await enterApp();return}catch(e){logoutLocal(true)}}})();
