const API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-membership';
const IMPORT_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-membership-import';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0});
const today=()=>new Date().toISOString().slice(0,10);
let token=localStorage.getItem('d12m_v22_token')||'', role=localStorage.getItem('d12m_v22_role')||'', data=null, page='dashboard', searchTerm='';
function setTheme(){if(localStorage.d12theme==='dark')document.documentElement.classList.add('dark')}
function toggleTheme(){document.documentElement.classList.toggle('dark');localStorage.d12theme=document.documentElement.classList.contains('dark')?'dark':'light'}
setTheme();
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2800)}
async function request(action,payload={},useAuth=true){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(useAuth&&token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!r.ok||!j.ok){if(r.status===401&&useAuth&&!['staff_login','member_login'].includes(action))logoutLocal(false);throw new Error(j.error||'Request failed.')}return j}
function saveSession(j){token=j.token;role=j.role;localStorage.setItem('d12m_v22_token',token);localStorage.setItem('d12m_v22_role',role)}
function logoutLocal(showWelcome=true){token='';role='';data=null;localStorage.removeItem('d12m_v22_token');localStorage.removeItem('d12m_v22_role');$('#app').classList.add('hidden');$('#publicStatus').classList.add('hidden');if(showWelcome){$('#welcome').classList.remove('hidden');$('#loginPanel').classList.add('hidden')}}
async function logout(){try{await request('logout')}catch(e){}logoutLocal(true)}
function chooseLogin(kind){const p=$('#loginPanel');p.classList.remove('hidden');if(kind==='member'){p.innerHTML=`<div class="login-head"><div><h2>Member Login</h2><p>Active members can view only their own membership.</p></div><button class="icon-btn" onclick="closeLoginPanel()">×</button></div><form id="memberLoginForm"><div class="field"><label>MEMBER ID</label><input name="member_code" placeholder="D12-2026-123456" required></div><div class="field"><label>MEMBER PIN</label><input name="pin" type="password" inputmode="numeric" required></div><button class="btn good block">View My Membership</button><div id="loginError" class="error"></div></form>`;$('#memberLoginForm').addEventListener('submit',memberLoginSubmit)}else{const a=kind==='admin';p.innerHTML=`<div class="login-head"><div><h2>${a?'Admin':'User'} Login</h2><p>${a?'Full system control.':'Register members and view membership status.'}</p></div><button class="icon-btn" onclick="closeLoginPanel()">×</button></div><form id="staffLoginForm"><input type="hidden" name="role" value="${kind}"><div class="field"><label>PASSWORD</label><input name="password" type="password" required autofocus></div><button class="btn ${a?'primary':'purple'} block">Sign In</button><div id="loginError" class="error"></div></form>`;$('#staffLoginForm').addEventListener('submit',staffLoginSubmit);setTimeout(()=>$('#staffLoginForm input[name=password]')?.focus(),50)}p.scrollIntoView({behavior:'smooth',block:'nearest'})}
function closeLoginPanel(){$('#loginPanel').classList.add('hidden')}
async function staffLoginSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),err=$('#loginError');err.textContent='';try{const j=await request('staff_login',{role:f.get('role'),password:f.get('password')},false);saveSession(j);await enterApp()}catch(x){err.textContent=x.message}}
async function memberLoginSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),err=$('#loginError');err.textContent='';try{const j=await request('member_login',{member_code:f.get('member_code'),pin:f.get('pin')},false);saveSession(j);await enterApp()}catch(x){err.textContent=x.message}}
async function enterApp(){$('#welcome').classList.add('hidden');$('#publicStatus').classList.add('hidden');$('#app').classList.remove('hidden');try{data=await request('bootstrap');role=data.role;localStorage.setItem('d12m_v22_role',role);page=role==='admin'?'dashboard':role==='user'?'status':'member';render()}catch(x){logoutLocal(true);toast(x.message)}}
function navItems(){if(role==='admin')return[['dashboard','⌂','Dashboard'],['members','♙','Members'],['payments','₦','Payments'],['renewals','↻','Renewals'],['scanner','▥','Scanner'],['settings','⚙','Settings']];if(role==='user')return[['register','＋','Register'],['status','♙','Status'],['scanner','▥','Scanner']];return[]}
function go(p){page=p;render()}
function setNav(){const items=navItems(),html=items.map(([p,i,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')">${i} &nbsp;${l}</button>`).join('');$('#nav').innerHTML=html;$('#mobileNav').innerHTML=items.map(([p,i,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')">${i}<br>${l}</button>`).join('');$('#mobileNav').style.setProperty('--count',Math.max(items.length,1));$('#roleBadge').textContent=(role||'').toUpperCase()+' ACCESS'}
function statusOf(m){return{label:m.membership_status||'INACTIVE',days:m.days_remaining??null,cls:m.membership_status==='ACTIVE'?'active':m.membership_status==='EXPIRING SOON'?'soon':m.membership_status==='EXPIRED'?'expired':'inactive',paused:!!m.perk_paused}}
function pill(m){const s=statusOf(m);return`<span class="pill ${s.cls}">${esc(s.label)}</span>${s.paused?'<span class="pill pause">BREAK & RUN PAUSE</span>':''}`}
function searchInput(){return`<div class="field search"><label>SEARCH</label><input id="memberSearch" value="${esc(searchTerm)}" placeholder="Name, ID or phone"></div>`}
function filteredMembers(){const q=searchTerm.trim().toLowerCase();return(data?.members||[]).filter(m=>!q||[m.full_name,m.member_code,m.phone,m.email].some(x=>String(x||'').toLowerCase().includes(q)))}
function attachSearch(){const el=$('#memberSearch');if(el)el.addEventListener('input',e=>{searchTerm=e.target.value;const host=$('#memberTableHost');if(host)host.innerHTML=memberStatusTable(filteredMembers(),role==='admin')})}
function memberStatusTable(rows,admin=false){if(!rows.length)return'<div class="empty">No members found.</div>';return`<div id="memberTableHost" class="table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Expiry</th><th>Days</th><th>Status</th><th>Break & Run</th>${admin?'<th>Admin Actions</th>':''}</tr></thead><tbody>${rows.map(m=>{const s=statusOf(m),eligible=['ACTIVE','EXPIRING SOON'].includes(s.label)&&!s.paused;return`<tr><td><b>${esc(m.full_name)}</b><br><small>${esc(m.member_code)}</small></td><td>${esc(m.current_plan_name||'—')}</td><td>${esc(m.expiry_date||'—')}</td><td>${s.days??'—'}${s.paused?`<br><small>Held until ${esc(m.break_run_pause_until)}</small>`:''}</td><td>${pill(m)}</td><td>${Number(m.break_run_wins||0)} win${Number(m.break_run_wins||0)===1?'':'s'}</td>${admin?`<td><div class="table-actions"><button class="btn small" onclick="openCard('${m.id}')">Card</button><button class="btn small perk" ${eligible?'': 'disabled'} onclick="breakRunWinner('${m.id}')">Break & Run Winner</button><button class="btn small" onclick="resetMemberPin('${m.id}')">Reset PIN</button><button class="btn small danger" onclick="deleteMember('${m.id}')">Delete</button></div></td>`:''}</tr>`}).join('')}</tbody></table></div>`}
function dashboardView(){const ms=data.members||[],ps=data.payments||[],active=ms.filter(m=>['ACTIVE','EXPIRING SOON'].includes(statusOf(m).label)).length,soon=ms.filter(m=>statusOf(m).label==='EXPIRING SOON').length,expired=ms.filter(m=>statusOf(m).label==='EXPIRED').length,revenue=ps.filter(p=>p.payment_status==='Paid').reduce((a,p)=>a+Number(p.amount),0),watch=ms.filter(m=>['EXPIRING SOON','EXPIRED'].includes(statusOf(m).label)).slice(0,10);return`<div class="grid kpis"><div class="card kpi"><span>ACTIVE MEMBERS</span><b>${active}</b></div><div class="card kpi"><span>EXPIRING SOON</span><b>${soon}</b></div><div class="card kpi"><span>EXPIRED</span><b>${expired}</b></div><div class="card kpi"><span>VERIFIED REVENUE</span><b>${money(revenue)}</b></div></div><div class="card section"><h2>Renewal Watch</h2>${memberStatusTable(watch,false)}</div><div class="card section"><div class="notice">Expired members cannot access the Member portal until Admin verifies a new membership payment and activation.</div></div>`}
function membersView(){return`<div class="card section"><div class="row split"><div><h2>Members</h2><p class="muted">Manage cards, Break & Run perks, PINs and member deletion.</p></div><button class="btn primary" onclick="openMemberModal()">＋ Register Member</button></div>${searchInput()}${memberStatusTable(filteredMembers(),true)}<div class="row import-row"><div class="field"><label>IMPORT CSV</label><input id="csvFile" type="file" accept=".csv,text/csv"></div><button class="btn" onclick="importCsv()">Import Members</button><button class="btn" onclick="exportCsv()">Export Status CSV</button></div></div>`}
function userRegisterView(){return`<div class="card section"><h2>Register a New Member</h2><p class="muted">User access can register members and view status. Payments and activation remain Admin-only.</p><button class="btn primary" onclick="openMemberModal()">＋ Open Registration Form</button></div><div class="card section"><h2>Member Status</h2>${searchInput()}${memberStatusTable(filteredMembers(),false)}</div>`}
function paymentsView(){const plans=(data.plans||[]).filter(p=>p.active&&p.price),ms=data.members||[],ps=data.payments||[];return`<div class="card section"><h2>Record Payment</h2><form id="paymentForm"><div class="row"><div class="field"><label>MEMBER *</label><select name="member_id" required><option value="">Select member</option>${ms.map(m=>`<option value="${m.id}">${esc(m.full_name)} — ${esc(m.member_code)}</option>`).join('')}</select></div><div class="field"><label>PLAN *</label><select name="plan_id" required><option value="">Select plan</option>${plans.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('')}</select></div><div class="field"><label>AMOUNT *</label><input name="amount" type="number" min="1" required></div><div class="field"><label>PAYMENT DATE</label><input name="payment_date" type="date" value="${today()}"></div><div class="field"><label>METHOD</label><select name="payment_method"><option>Transfer</option><option>Cash</option><option>POS</option><option>Other</option></select></div><div class="field"><label>REFERENCE</label><input name="reference"></div></div><button class="btn primary">Record as Pending</button></form></div><div class="card section"><h2>Payment Register</h2><div class="table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Amount</th><th>Status</th><th>Date</th><th>Activation</th><th>Action</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.d12_membership_members?.full_name||'Unknown')}</td><td>${esc(p.d12_membership_plans?.name||'—')}</td><td><b>${money(p.amount)}</b></td><td>${esc(p.payment_status)}</td><td>${esc(p.payment_date||'—')}</td><td>${esc(p.activation_date||'—')}</td><td>${p.payment_status==='Pending'?`<div class="table-actions"><input id="act-${p.id}" type="date" value="${today()}" class="compact-date"><button class="btn small good" onclick="verifyPayment('${p.id}')">Verify / Activate</button><button class="btn small danger" onclick="rejectPayment('${p.id}')">Reject</button></div>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function renewalsView(){const rows=(data.members||[]).filter(m=>['EXPIRING SOON','EXPIRED'].includes(statusOf(m).label));return`<div class="card section"><h2>Renewal Queue</h2>${memberStatusTable(rows,false)}</div>`}
function scannerView(){return`<div class="card section"><h2>Scan Membership Card</h2><p class="muted">Scan the Code 128 barcode or type the token.</p><form id="scanForm"><div class="field"><label>BARCODE</label><input id="scanInput" class="scan-input" autocomplete="off" autofocus></div><button class="btn primary">Check Card</button></form><div id="scanResult"></div></div>`}
function settingsView(){return`<div class="card section"><h2>Club Rates & Alerts</h2><form id="settingsForm"><div class="row"><div class="field"><label>DAILY RATE AFTER EXPIRY (₦)</label><input name="daily_rate" type="number" min="0" value="${Number(data.settings?.daily_rate||3000)}" required></div><div class="field"><label>EXPIRING SOON WINDOW (DAYS)</label><input name="expiring_soon_days" type="number" min="1" max="60" value="${Number(data.settings?.expiring_soon_days||7)}" required></div></div><button class="btn primary">Save Club Settings</button></form></div><div class="card section"><h2>Membership Plans</h2><div class="grid plans">${(data.plans||[]).map(p=>`<form class="card plan planForm" data-id="${p.id}"><h3>${esc(p.name)}</h3><p class="muted">${p.period_value} ${esc(p.period_unit)}</p><div class="field"><label>PRICE (₦)</label><input name="price" type="number" min="1" value="${p.price||''}"></div><label class="check"><input name="active" type="checkbox" ${p.active?'checked':''}> Active plan</label><button class="btn block">Save Plan</button></form>`).join('')}</div></div><div class="grid settings-grid"><div class="card section"><h2>User Login Password</h2><form id="userPasswordForm"><div class="field"><label>NEW USER PASSWORD</label><input name="new_password" type="password" minlength="4" required></div><div class="field"><label>CONFIRM PASSWORD</label><input name="confirm_password" type="password" minlength="4" required></div><button class="btn purple">Change User Password</button></form></div><div class="card section"><h2>Admin Password</h2><p class="muted">Enter the current/default Admin password before choosing a new one.</p><form id="adminPasswordForm"><div class="field"><label>CURRENT / DEFAULT ADMIN PASSWORD</label><input name="current_password" type="password" required></div><div class="field"><label>NEW ADMIN PASSWORD</label><input name="new_password" type="password" minlength="8" required></div><div class="field"><label>CONFIRM NEW PASSWORD</label><input name="confirm_password" type="password" minlength="8" required></div><button class="btn primary">Change Admin Password</button></form></div></div>`}
function memberPortalView(){const m=data.member,s=statusOf(m);return`<div class="card status-hero"><div class="row split"><div><div class="muted tiny">MY D12 MEMBERSHIP</div><h2>${esc(m.full_name)}</h2><div class="muted">${esc(m.member_code)}</div></div>${pill(m)}</div><div class="status-grid"><div><span>MEMBERSHIP TYPE</span><b>${esc(m.current_plan_name||'Not active')}</b></div><div><span>EXPIRATION DATE</span><b>${esc(m.expiry_date||'—')}</b></div><div><span>DAYS REMAINING</span><b>${s.days??'—'}</b></div><div><span>BREAK & RUN WINS</span><b>${Number(m.break_run_wins||0)}</b></div></div>${s.paused?`<div class="perk-note">🏆 Break & Run Winner perk active. Countdown is held until ${esc(m.break_run_pause_until)}.</div>`:''}<form id="memberPinForm"><div class="row"><div class="field"><label>NEW MEMBER PIN</label><input name="new_pin" type="password" inputmode="numeric" minlength="4" maxlength="12" required></div><div class="field"><label>CONFIRM PIN</label><input name="confirm_pin" type="password" inputmode="numeric" minlength="4" maxlength="12" required></div></div><button class="btn">Change My PIN</button></form><div class="row"><button class="btn primary" onclick="openCard('${m.id}')">View Membership Card</button><button class="btn danger" onclick="logout()">Sign Out</button></div></div>`}
function render(){setNav();const title=$('#pageTitle'),sub=$('#pageSub'),view=$('#view'),actions=$('#topActions');if(role==='member'){title.textContent='My Membership';sub.textContent='Your personal active membership.';actions.innerHTML=`<button class="btn" onclick="toggleTheme()">◐ Theme</button><button class="btn danger" onclick="logout()">Sign Out</button>`;view.innerHTML=memberPortalView();wireView();return}const map={dashboard:['Dashboard','Membership health at a glance.'],members:['Members','Manage registered D12 members.'],payments:['Payments','Verify payment before activation or reactivation.'],renewals:['Renewals','Members needing renewal attention.'],scanner:['Card Scanner','Scan a D12 membership barcode.'],settings:['Settings','Admin-only pricing and login controls.'],register:['Register Members','Register members and create cards.'],status:['Membership Status','View member subscription status.']},m=map[page]||map.status;title.textContent=m[0];sub.textContent=m[1];actions.innerHTML=`<button class="btn" onclick="toggleTheme()">◐ Theme</button>${role!=='member'?'<button class="btn wide" onclick="openMemberModal()">＋ Member</button>':''}${role==='admin'?'<button class="btn primary wide" onclick="go(\'payments\')">＋ Payment</button>':''}<button class="btn danger" onclick="logout()">Sign Out</button>`;view.innerHTML=page==='dashboard'?dashboardView():page==='members'?membersView():page==='payments'?paymentsView():page==='renewals'?renewalsView():page==='scanner'?scannerView():page==='settings'?settingsView():page==='register'?userRegisterView():`<div class="card section"><h2>Member Status</h2>${searchInput()}${memberStatusTable(filteredMembers(),false)}</div>`;wireView()}
