function wireView(){attachSearch();$('#paymentForm')?.addEventListener('submit',recordPayment);$('#scanForm')?.addEventListener('submit',scanCard);$('#settingsForm')?.addEventListener('submit',saveSettings);$$('.planForm').forEach(f=>f.addEventListener('submit',savePlan));$('#userPasswordForm')?.addEventListener('submit',changeUserPassword);$('#adminPasswordForm')?.addEventListener('submit',changeAdminPassword);$('#memberPinForm')?.addEventListener('submit',changeMemberPin)}
function openMemberModal(){$('#memberModal').classList.remove('hidden');setTimeout(()=>$('#memberForm input[name=full_name]')?.focus(),30)}
function closeModal(id){$('#'+id).classList.add('hidden')}
async function registerMember(e){e.preventDefault();const form=e.currentTarget,payload=Object.fromEntries(new FormData(form).entries());try{const j=await request('add_member',payload);form.reset();closeModal('memberModal');await refresh();toast('Member registered successfully.');openCard(j.member.id,j.member_pin)}catch(x){toast(x.message)}}
async function refresh(){data=await request('bootstrap');role=data.role;render()}
async function deleteMember(id){const m=(data.members||[]).find(x=>x.id===id);if(!m)return;if(!confirm(`Permanently delete ${m.full_name}?\n\nThis removes the member and their membership/payment history. This action cannot be undone.`))return;try{const j=await request('delete_member',{id});await refresh();toast(`${j.deleted_name} deleted.`)}catch(x){toast(x.message)}}
async function breakRunWinner(id){const m=(data.members||[]).find(x=>x.id===id);if(!m)return;if(!confirm(`Confirm ${m.full_name} as a Break & Run Winner?\n\nTheir membership countdown will pause for exactly 6 days.`))return;try{const j=await request('break_run_winner',{id});await refresh();toast(`6-day pause active until ${j.pause_until}.`)}catch(x){toast(x.message)}}
async function resetMemberPin(id){if(!confirm('Reset this member PIN? Any current member session will be signed out.'))return;try{const j=await request('reset_member_pin',{id});openCard(id,j.member_pin);toast('New member PIN generated.')}catch(x){toast(x.message)}}
async function changeMemberPin(e){e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=String(f.get('new_pin')||''),c=String(f.get('confirm_pin')||'');if(p!==c)return toast('PINs do not match.');try{await request('change_member_pin',{new_pin:p});form.reset();toast('PIN changed.')}catch(x){toast(x.message)}}
async function recordPayment(e){e.preventDefault();const form=e.currentTarget,p=Object.fromEntries(new FormData(form).entries());try{await request('record_payment',p);form.reset();await refresh();toast('Payment recorded as Pending.')}catch(x){toast(x.message)}}
async function verifyPayment(id){const activation=$('#act-'+CSS.escape(id))?.value;if(!activation)return toast('Select activation date.');if(!confirm('Verify this payment and activate/reactivate the member subscription?'))return;try{const j=await request('verify_payment',{id,activation_date:activation});await refresh();toast('Membership active until '+j.expiry_date)}catch(x){toast(x.message)}}
async function rejectPayment(id){if(!confirm('Reject this pending payment?'))return;try{await request('reject_payment',{id});await refresh();toast('Payment rejected.')}catch(x){toast(x.message)}}
async function saveSettings(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await request('save_settings',{daily_rate:Number(f.get('daily_rate')),expiring_soon_days:Number(f.get('expiring_soon_days'))});await refresh();toast('Settings saved.')}catch(x){toast(x.message)}}
async function savePlan(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await request('save_plan',{id:e.currentTarget.dataset.id,price:Number(f.get('price')||0),active:f.get('active')==='on'});await refresh();toast('Plan saved.')}catch(x){toast(x.message)}}
async function changeUserPassword(e){e.preventDefault();const form=e.currentTarget,f=new FormData(form),p=String(f.get('new_password')||''),c=String(f.get('confirm_password')||'');if(p!==c)return toast('Passwords do not match.');try{await request('change_user_password',{new_password:p});form.reset();toast('User password changed.')}catch(x){toast(x.message)}}
async function changeAdminPassword(e){e.preventDefault();const form=e.currentTarget,f=new FormData(form),n=String(f.get('new_password')||''),c=String(f.get('confirm_password')||'');if(n!==c)return toast('New Admin passwords do not match.');try{await request('change_admin_password',{current_password:f.get('current_password'),new_password:n});form.reset();toast('Admin password changed successfully.')}catch(x){toast(x.message)}}
function cardStatusHtml(m,dailyRate=null){const s=statusOf(m);return`<div class="card status-hero"><div class="row split"><div><div class="muted tiny">D12 MEMBERSHIP STATUS</div><h2>${esc(m.full_name)}</h2><div class="muted">${esc(m.member_code)}</div></div>${pill(m)}</div><div class="status-grid"><div><span>MEMBERSHIP TYPE</span><b>${esc(m.current_plan_name||'Not active')}</b></div><div><span>EXPIRATION DATE</span><b>${esc(m.expiry_date||'—')}</b></div><div><span>DAYS REMAINING</span><b>${s.days??'—'}</b></div><div><span>BREAK & RUN WINS</span><b>${Number(m.break_run_wins||0)}</b></div></div>${s.paused?`<div class="perk-note">Countdown paused until ${esc(m.break_run_pause_until)}.</div>`:''}${s.label==='EXPIRED'&&dailyRate!=null?`<div class="notice">Expired membership: daily rate is ${money(dailyRate)} until renewal.</div>`:''}</div>`}
async function scanCard(e){e.preventDefault();const raw=$('#scanInput').value.trim(),card_token=raw.replace(/^D12M:/i,'').replace(/^.*[?&]card=/,'').split('&')[0];if(!card_token)return;try{const j=await request('card_status',{card_token},false);$('#scanResult').innerHTML=cardStatusHtml(j.member,j.daily_rate);$('#scanInput').value='';$('#scanInput').focus()}catch(x){$('#scanResult').innerHTML=`<div class="notice error">${esc(x.message)}</div>`}}
function openCard(id,loginPin=null){const pool=role==='member'?[data.member]:(data.members||[]),m=pool.find(x=>x.id===id);if(!m)return toast('Member card not found.');const s=statusOf(m),base=location.origin+location.pathname,live=base+'?card='+encodeURIComponent(m.card_token||'');$('#cardMount').innerHTML=`<div id="printCard" class="membership-card"><div class="mc-head"><div class="mc-logo">D12 CUE CLUB<small>OFFICIAL MEMBERSHIP CARD</small></div><div class="mc-status">${esc(s.label)}</div></div><div class="mc-name">${esc(m.full_name)}</div><div class="mc-id">MEMBER ID · ${esc(m.member_code)}</div><div class="mc-grid"><div><span>MEMBERSHIP</span><b>${esc(m.current_plan_name||'INACTIVE')}</b></div><div><span>EXPIRES</span><b>${esc(m.expiry_date||'—')}</b></div><div><span>B&R WINS</span><b>${Number(m.break_run_wins||0)}</b></div></div><a href="${esc(live)}" target="_blank"><div class="barcode-box"><svg id="memberBarcode"></svg></div></a><div class="mc-foot">SCAN TO CHECK LIVE MEMBERSHIP STATUS</div></div>${loginPin?`<div class="notice center"><b>Member Login PIN: ${esc(loginPin)}</b><br><small>Give this PIN privately to the member. It is shown only now.</small></div>`:''}<div class="row"><button class="btn primary" onclick="window.print()">Print Card</button><a class="btn" href="${esc(live)}" target="_blank">Open Live Status</a></div>`;$('#cardModal').classList.remove('hidden');setTimeout(()=>{if(window.JsBarcode&&m.card_token)JsBarcode('#memberBarcode','D12M:'+m.card_token,{format:'CODE128',displayValue:false,height:54,width:1.3,margin:0,background:'#fff',lineColor:'#000'})},50)}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const h=lines.shift().split(',').map(x=>x.trim().toLowerCase());return lines.map(line=>{const c=line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')),r={};h.forEach((k,i)=>r[k]=c[i]||'');return r})}
async function importCsv(){const file=$('#csvFile')?.files?.[0];if(!file)return toast('Choose a CSV file.');try{const rows=parseCsv(await file.text()),r=await fetch(IMPORT_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({rows})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Import failed.');await refresh();toast(`${j.count} members imported. Imported members use PIN 2017 until changed.`)}catch(x){toast(x.message)}}
function exportCsv(){const rows=[['Member ID','Full Name','Phone','Email','Plan','Expiry','Days Remaining','Status','Break & Run Wins'],...(data.members||[]).map(m=>[m.member_code,m.full_name,m.phone||'',m.email||'',m.current_plan_name||'',m.expiry_date||'',m.days_remaining??'',m.membership_status||'',m.break_run_wins||0])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='D12_Membership_Status_V2_2.csv';a.click();URL.revokeObjectURL(a.href)}
$('#memberForm').addEventListener('submit',registerMember);$$('[data-login]').forEach(b=>b.addEventListener('click',()=>chooseLogin(b.dataset.login)));$('#themeWelcome').addEventListener('click',toggleTheme);
(async()=>{const card=new URLSearchParams(location.search).get('card');if(card){$('#welcome').classList.add('hidden');$('#publicStatus').classList.remove('hidden');try{const j=await request('card_status',{card_token:card},false);$('#publicStatus').innerHTML=`<div class="public-box">${cardStatusHtml(j.member,j.daily_rate)}<a class="btn" href="${location.pathname}">Back to Login</a></div>`}catch(x){$('#publicStatus').innerHTML=`<div class="public-box"><div class="card section"><h2>Card Not Found</h2><p>${esc(x.message)}</p></div></div>`}return}if(token){$('#welcome').classList.add('hidden');$('#app').classList.remove('hidden');try{await enterApp()}catch(e){logoutLocal(true)}}})();
